//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursoMvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cursomvcEntities : DbContext
    {
        public cursomvcEntities()
            : base("name=cursomvcEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categoryOfMachines> categoryOfMachines { get; set; }
        public virtual DbSet<cstate> cstate { get; set; }
        public virtual DbSet<items> items { get; set; }
        public virtual DbSet<location> location { get; set; }
        public virtual DbSet<lpn> lpn { get; set; }
        public virtual DbSet<machines> machines { get; set; }
        public virtual DbSet<purchaseOrder> purchaseOrder { get; set; }
        public virtual DbSet<sparepartLocation> sparepartLocation { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
