//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursoMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class items
    {
        public int id { get; set; }
        public string partnumber { get; set; }
        public string description { get; set; }
        public byte[] ilustration { get; set; }
        public int idmachine { get; set; }
        public int quantity { get; set; }
        public Nullable<int> idstatus { get; set; }
    
        public virtual cstate cstate { get; set; }
    }
}
