//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursoMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lpn
    {
        public int id { get; set; }
        public string lpn1 { get; set; }
        public string partumber { get; set; }
        public Nullable<int> idocation { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> idstatus { get; set; }
    
        public virtual cstate cstate { get; set; }
    }
}
