//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursoMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class machines
    {
        public int id { get; set; }
        public string machineName { get; set; }
        public int idCategory { get; set; }
        public Nullable<int> idStatus { get; set; }
    
        public virtual categoryOfMachines categoryOfMachines { get; set; }
    }
}
