//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursoMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sparepartLocation
    {
        public int id { get; set; }
        public Nullable<int> idlocation { get; set; }
        public string username { get; set; }
        public Nullable<System.DateTime> dateUpdate { get; set; }
        public Nullable<int> quantity { get; set; }
        public string partnumber { get; set; }
        public string lpn { get; set; }
    
        public virtual location location { get; set; }
    }
}
